PERMISSIONS = {
    "wallets.read",
    "wallets.manage",
    "payments.read",
    "payments.create",
    "payments.refund",
    "transfers.create",
    "deposits.create",
    "withdrawals.create",
    "withdrawals.review",
    "ledger.read",
    "reconciliation.manage",
    "users.manage",
    "compliance.review",
    "reports.export",
    "webhooks.manage",
    "api_keys.manage",
    "audit.read",
    "fees.manage",
    "limits.manage",
    "adjustments.create",
}

ROLE_PERMISSIONS = {
    "platform_administrator": PERMISSIONS,
    "operations_manager": {
        "wallets.read",
        "wallets.manage",
        "payments.read",
        "withdrawals.review",
        "ledger.read",
        "reconciliation.manage",
        "compliance.review",
        "reports.export",
        "audit.read",
    },
    "compliance_reviewer": {"wallets.read", "payments.read", "compliance.review", "audit.read"},
    "finance_reviewer": {
        "wallets.read",
        "payments.read",
        "ledger.read",
        "reconciliation.manage",
        "reports.export",
        "adjustments.create",
    },
    "merchant_administrator": {
        "wallets.read",
        "payments.read",
        "payments.create",
        "payments.refund",
        "withdrawals.create",
        "reports.export",
        "webhooks.manage",
        "api_keys.manage",
        "users.manage",
    },
    "merchant_operator": {
        "wallets.read",
        "payments.read",
        "payments.create",
        "payments.refund",
        "withdrawals.create",
    },
    "customer": {
        "wallets.read",
        "payments.read",
        "payments.create",
        "transfers.create",
        "deposits.create",
        "withdrawals.create",
    },
    "read_only_auditor": {
        "wallets.read",
        "payments.read",
        "ledger.read",
        "audit.read",
        "reports.export",
    },
}
